names = [
    "Mateusz Roszkowski redbull",
    "Szymon Puchyrski haas",
    "Krystian Michalczuk haas",
    "Kacper Zabagło mercedes",
    "Kamil Stachura redbull",
    "Kamil Dziuk renault",
    "Sebastian Ocimek mclaren",
    "Andrzej Magiera-Gorzka racingpoint",
    "Jakub Zimmer ferrari",
    "Mateusz Zieliński ferrari",
    "Patryk Janusiewicz alphatauri",
    "Krzysztof Winikajtys mercedes",
    "Kamil Kubów williams",
    "Kasper Pałka williams",
    "Przemysław Dubowski renault",
    "Piotr Czerniawski alfaromeo",
    "Kryspin Słomiński racingpoint",
    "Wojtek Grzybowski alphatauri",
    "Filip Siudak alfaromeo",
    "Szymon Kulik mclaren"
];

grid = [
    "Michalczuk",
    "Kulik",
    "Siudak",
    "Dubowski",
    "Pałka",
    "Janusiewicz",
    "Kubów",
    "Dubowski",
    "Czerniawski",
    "Słomiński",
    "Grzybowski",
    "Zieliński",
    "Zimmer",
    "Magiera-Gorzka",
    "Ocimek",
    "Dziuk",
    "Stachura",
    "Zabagło",
    "Puchyrski",
    "Roszkowski"
];